# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
pair_wrapper <- function(j, jp, n_j, n_jp, p, alpha_j, alpha_jp, x, beta, lxi, artanhrho, ind = 0L, verboseS = FALSE, verboseSind = FALSE) {
    .Call(`_gammaFrailty_pair_wrapper`, j, jp, n_j, n_jp, p, alpha_j, alpha_jp, x, beta, lxi, artanhrho, ind, verboseS, verboseSind)
}

#' @export
ncl <- function(theta, data, X, printFLAG = FALSE, PAIRS_RANGE = 100L) {
    .Call(`_gammaFrailty_ncl`, theta, data, X, printFLAG, PAIRS_RANGE)
}

#' @export
gammaFrailty <- function(THETA_INIT, DATA, X, MAXT, BURN, STEPSIZE, STEPSIZE0, SCALEVEC, NU, METHODFLAG = 0L, VERBOSEFLAG = FALSE, STEPSIZEFLAG = FALSE, par1 = 1, par2 = 1, par3 = .75, PAIRS_RANGE = 100L, SCALEFLAG = FALSE) {
    .Call(`_gammaFrailty_gammaFrailty`, THETA_INIT, DATA, X, MAXT, BURN, STEPSIZE, STEPSIZE0, SCALEVEC, NU, METHODFLAG, VERBOSEFLAG, STEPSIZEFLAG, par1, par2, par3, PAIRS_RANGE, SCALEFLAG)
}

#' @export
zofr_cpp <- function(r) {
    .Call(`_gammaFrailty_zofr_cpp`, r)
}

#' @export
rofz_cpp <- function(z) {
    .Call(`_gammaFrailty_rofz_cpp`, z)
}

#' @export
drofz_cpp <- function(z) {
    .Call(`_gammaFrailty_drofz_cpp`, z)
}

#'@export
rmultinom_wrapper <- function(prob, classes, batch, K) {
    .Call(`_gammaFrailty_rmultinom_wrapper`, prob, classes, batch, K)
}

#' @export
sampleJ <- function(THETA, DATA, X, PRINTFLAG = FALSE, PAIRS_RANGE = 100L) {
    .Call(`_gammaFrailty_sampleJ`, THETA, DATA, X, PRINTFLAG, PAIRS_RANGE)
}

#' @export
sampleH <- function(THETA, DATA, X, PRINTFLAG = FALSE, INVERTFLAG = FALSE, PAIRS_RANGE = 100L) {
    .Call(`_gammaFrailty_sampleH`, THETA, DATA, X, PRINTFLAG, INVERTFLAG, PAIRS_RANGE)
}

#' @export
sampleVar <- function(THETA, DATA, X, NU, METHOD, RANGE, TOTFLAG, PRINTFLAG, PAIRS_RANGE = 100L) {
    .Call(`_gammaFrailty_sampleVar`, THETA, DATA, X, NU, METHOD, RANGE, TOTFLAG, PRINTFLAG, PAIRS_RANGE)
}

