# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
pair_wrapper <- function(j, jp, n_j, n_jp, p, alpha_j, alpha_jp, x, beta, lxi, artanhrho, ind = 0L, verboseS = FALSE, verboseSind = FALSE, STRUCT = 0L) {
    .Call(`_gammaFrailty_pair_wrapper`, j, jp, n_j, n_jp, p, alpha_j, alpha_jp, x, beta, lxi, artanhrho, ind, verboseS, verboseSind, STRUCT)
}

#' @export
ncl <- function(theta, data, X, printFLAG = FALSE, PAIRS_RANGE = 100L, STRUCT = 0L) {
    .Call(`_gammaFrailty_ncl`, theta, data, X, printFLAG, PAIRS_RANGE, STRUCT)
}

#' @export
gammaFrailty <- function(THETA_INIT, DATA, X, STRUCT, MAXT, BURN, STEPSIZE, SCALEVEC, NU, METHODFLAG = 0L, VERBOSEFLAG = FALSE, par1 = 1, par2 = 1, par3 = .75, PAIRS_RANGE = 100L, STEPSIZEFLAG = 1L) {
    .Call(`_gammaFrailty_gammaFrailty`, THETA_INIT, DATA, X, STRUCT, MAXT, BURN, STEPSIZE, SCALEVEC, NU, METHODFLAG, VERBOSEFLAG, par1, par2, par3, PAIRS_RANGE, STEPSIZEFLAG)
}

#' @export
gammaFrailty2 <- function(THETA_INIT, DATA, X, STRUCT, MAXT, BURN, STEPSIZE, SCALEVEC, NU, METHODFLAG = 0L, VERBOSEFLAG = FALSE, PAR1 = 1, PAR2 = 1, PAR3 = .75, STEPSIZEFLAG = 1L, SEED = 123L, SAMPLING_WINDOW = 1L) {
    .Call(`_gammaFrailty_gammaFrailty2`, THETA_INIT, DATA, X, STRUCT, MAXT, BURN, STEPSIZE, SCALEVEC, NU, METHODFLAG, VERBOSEFLAG, PAR1, PAR2, PAR3, STEPSIZEFLAG, SEED, SAMPLING_WINDOW)
}

#' @export
zofr_cpp <- function(r) {
    .Call(`_gammaFrailty_zofr_cpp`, r)
}

#' @export
rofz_cpp <- function(z) {
    .Call(`_gammaFrailty_rofz_cpp`, z)
}

#' @export
drofz_cpp <- function(z) {
    .Call(`_gammaFrailty_drofz_cpp`, z)
}

#'@export
rmultinom_wrapper <- function(prob, classes, batch, K) {
    .Call(`_gammaFrailty_rmultinom_wrapper`, prob, classes, batch, K)
}

#'@export
hyper_sampling <- function(K, N, SEED) {
    .Call(`_gammaFrailty_hyper_sampling`, K, N, SEED)
}

#'@export
unit_sampling <- function(N, SEED) {
    .Call(`_gammaFrailty_unit_sampling`, N, SEED)
}

#'@export
components_given_unit <- function(UNIT, K) {
    .Call(`_gammaFrailty_components_given_unit`, UNIT, K)
}

#'@export
bernoulli_sampling <- function(K, N, PROB) {
    .Call(`_gammaFrailty_bernoulli_sampling`, K, N, PROB)
}

#'@export
index_to_component <- function(P, N, INDEX) {
    .Call(`_gammaFrailty_index_to_component`, P, N, INDEX)
}

#' @export
sampleJ <- function(THETA, DATA, X, STRUCT, PRINTFLAG = FALSE, PAIRS_RANGE = 100L) {
    .Call(`_gammaFrailty_sampleJ`, THETA, DATA, X, STRUCT, PRINTFLAG, PAIRS_RANGE)
}

#' @export
sampleH <- function(THETA, DATA, X, STRUCT, PRINTFLAG = FALSE, INVERTFLAG = FALSE, PAIRS_RANGE = 100L) {
    .Call(`_gammaFrailty_sampleH`, THETA, DATA, X, STRUCT, PRINTFLAG, INVERTFLAG, PAIRS_RANGE)
}

#' @export
sampleVar <- function(THETA, DATA, X, STRUCT, NU, METHOD, RANGE, TOTFLAG, PRINTFLAG, PAIRS_RANGE = 100L) {
    .Call(`_gammaFrailty_sampleVar`, THETA, DATA, X, STRUCT, NU, METHOD, RANGE, TOTFLAG, PRINTFLAG, PAIRS_RANGE)
}

